[ApplicationPreferences]
AutoUpdate=false
CurrentLocale=en
EarliestChangeLog=4.42.23291
LastFTEStep=Finish
QuickTourWidgetShown=true
SideloadedMode=true
StylusTipWarning=true
WifiRegulatoryDomain=US

sleepOnNextBoot=false
syncOnNextBoot=false

[DialogSettings]
InstapaperJitShown=true
ReleaseNotesShown=true

[FeatureSettings]
ExcludeSyncFolders=(\\.(?!kobo|adobe).+|([^.][^/]*/)+\\..+|.*\\.md|.*\\.png|.*\\.txt)
Screensavers=true

[PowerOptions]
FullscreenCoverStretch=true
ShowBookCover=true

[Reading]
numPartialUpdatePageTurns=5

[DeveloperSettings]
AutoUsbGadget=true
